name: gym_detector_ios
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_timer_countdown: ^1.0.5 # 倒计时器 
  image_picker: ^0.8.5+3 # 单图片照片采取器
  dotted_border: ^2.0.0
  video_thumbnail: ^0.5.1 # 视频压缩图
  shared_preferences: ^2.3.2 # 暂存用户偏好数据
  fl_chart:   #绘制曲线图
  http:  # http请求
  provider: ^6.0.5 #监听器
  cloudinary_public: ^0.23.1 #图片云床
  flutter_screenutil: ^5.6.1 # 屏幕自适应
  multi_image_picker_view: ^1.1.0 #多图片采取器
  video_player: ^2.9.2 #视频时长获取
  crypto: ^3.0.6  #哈希加密密码
  bcrypt: ^1.1.3
  cached_network_image: ^3.4.1  #图片缓存


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gymplan_images/
    - assets/user_images/
    - assets/dynamic_images/
    - assets/bar_images/
    - assets/bodydata_images/
    - assets/logo/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf